sonar.verbose=true
sonar.organization=abhikey01
sonar.projectKey=abhikey01_Devops012
sonar.projectName=Devops012
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xmlDevops01
